version: '3.8'
services:
  db:
    image: "postgres:latest"
    container_name: todo-application-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=todoApplication
      - POSTGRES_PASSWORD=todoApplication
    volumes:
      - pgdata:/var/lib/postgresql/data
